# Generated by Django 4.2.23 on 2025-08-27 18:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='uploads/temp')),
                ('sha256', models.CharField(db_index=True, max_length=64, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.BigIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
