# Generated by Django 4.2.23 on 2025-08-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_saved_bytes', models.BigIntegerField(default=0)),
            ],
        ),
    ]
